---
kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: mycart
spec:
  selector:
    app: mycart
    layer: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
